title:            Ralph YY's Blog
description:      Ralph YY's Blog
url:              # Site url, without a slash at the end.
signoff:          # Your name.
disqus_shortname: ycj28cgithubio # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links: # mid navigation bar
  - name:         About
    url:          /about
  - name:         Tech&IT
    url:          /
  - name:         LifeStyle
    url:          /lifeblog
  - name:         GitHub
    url:          https://github.com/ycj28c
    external:     true
nav: # side bar navigation
  Home:           
    - '/'
  Tech&IT:           
    - '/'
    - { Categories: '/categories/category/' }
    - { Tags: '/categories/tag/' }
  About:          
    - '/about/'
  Github Project: 
    - 'https://github.com/ycj28c'
# Where are tags and categories displayed
tag_page: '/categories/tag/'
category_page: '/categories/category/'
highlighter:      rouge
permalink:        pretty
version: 1.0.0
sass:
  style: compressed
  sass_dir: stylesheets/_scss
# About/contact
author:
  name: Ralph Yang
  description: hello.
  gravatar: # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/chengjiaoyang
    github:    https://github.com/ycj28c
    # facebook:  <hide>
    twitter:   https://twitter.com/
    # weibo:     http://weibo.com/11111
    # email:     http://www.google.com/recaptcha/mailhide/d?k=111111111111==&c=11111111111
