// Generated by CoffeeScript 1.6.3
jQuery(function() {
  return $.each($("[data-time]"), function(index, ele) {
    return $(ele).html(prettyDate(new Date($(this).data("time"))));
  });
});

var didScroll;
var lastScrollTop = 0;
var delta = 5;
var navbarHeight = $('.masthead').outerHeight();

$(window).scroll(function(event){
    didScroll = true;
});

setInterval(function() {
    if (didScroll) {
        hasScrolled();
        didScroll = false;
		adjustFlyBar();
    }
}, 250);

function adjustFlyBar(){
	console.log("1111"+ document.querySelector(".masthead").offsetHeight );
	console.log("2222"+ document.querySelector(".masthead").clientHeight );
	console.log("3333"+ document.querySelector(".masthead").scrollHeight );
	var flybarHeight = document.querySelector(".masthead").clientHeight;
	var scrollOffSet = window.pageYOffset;
	document.querySelector(".masthead").style.marginTop = scrollOffSet - flybarHeight;
}

function hasScrolled() {
    var st = $(this).scrollTop();
    
    // Make sure they scroll more than delta
    if(Math.abs(lastScrollTop - st) <= delta)
        return;
    
    // If they scrolled down and are past the navbar, add class .nav-up.
    // This is necessary so you never see what is "behind" the navbar.
    if (st > lastScrollTop && st > navbarHeight){
        // Scroll Down
		if(!document.querySelector('#sidebar-checkbox').checked){
			$('.masthead').removeClass('nav-down').addClass('nav-up');
		}
    } else {
        // Scroll Up
		if(st + $(window).height() < $(document).height()) {
			$('.masthead').removeClass('nav-up').addClass('nav-down');
		}
    }
    
    lastScrollTop = st;
}